---
# tasks file for network_vpc
# - name: IOS Devices
#   include_tasks: netconf.yml
#   when: device_type == "ios" and ospf is defined
- name: NX-OS Devices
  include_tasks: nxapi.yml
  when: device_type == "nxos" and vpc is defined
